workflows:
  web-build:
    name: Web Build (New)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Prepare Web Build (Inject Services)
        script: |
          sh scripts/prepare_web_build.sh
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Flutter build web
        script: |
          # Build for Web
          # Note: If deploying to GitHub Pages Project site, add --base-href /repo-name/
          flutter build web --release --wasm
    artifacts:
      - build/web/**
    publishing:
      email:
        recipients:
          - hussein@mooseshel.com

  ios-build:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        provisioning_profiles:
          - FayRunAppStore
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.fayrun.app"
        APP_STORE_APPLE_ID: 6758923362
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - hussein@mooseshel.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false
